services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-Training#2024}
      - DB_NAME=${DB_NAME:-final_project}
      - JWT_SECRET=${JWT_SECRET:-your_secret_key}
    depends_on:
      - db
    command: >
      sh -c "
        /usr/local/bin/wait-for-it db:5432 --timeout=30 --strict -- echo 'Database is up' &&
        echo 'Checking if database exists' &&
        PGPASSWORD=$$DB_PASSWORD psql -h $$DB_HOST -U $$DB_USER -lqt | cut -d '|' -f 1 | grep -qw $$DB_NAME || {
          echo 'Creating database' &&
          npx sequelize-cli db:create;
        } &&
        echo 'Running migrations' &&
        npx sequelize-cli db:migrate &&
        echo 'Seeding reference data' &&
        npx sequelize-cli db:seed:all &&
        echo 'Starting application' &&
        node server.js
      "

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-Training#2024}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: